[package]
name = "tauri-plugin-data"
version = "0.1.0"
authors = ["You"]
description = "Tauri plugin for data"
edition = "2024"
exclude = ["/dist-js", "/guest-js", "/node_modules"]
links = "tauri-plugin-data"

[dependencies]
tauri = { workspace = true }
shell360-data = { path = "../crates/shell360-data" }

[build-dependencies]
tauri-plugin = { workspace = true, features = ["build"] }
