[workspace]
members = [
  "src-tauri",
  "tauri-plugin-mobile",
  "tauri-plugin-ssh",
  "tauri-plugin-data",
]
resolver = "2"

[workspace.dependencies]
tauri = "2.8.5"
tauri-build = "2.4.1"
tauri-plugin = "2.4.0"
serde = "1.0.228"
serde_json = "1.0.143"
thiserror = "2.0.17"
