packages:
  - desktop
  - mobile
  - packages/jsb
  - packages/bridge
  - packages/shared
  - crates/tauri-plugin-ssh
  - crates/tauri-plugin-data
  - crates/tauri-plugin-pty
allowBuilds:
  core-js: true
