packages:
  - desktop
  - mobile
  - shared
  - tauri-plugin-mobile
  - tauri-plugin-ssh
  - tauri-plugin-data
  - tauri-plugin-pty
allowBuilds:
  core-js: true
minimumReleaseAgeExclude:
  - '@rsbuild/core@2.0.15'
  - '@rstest/core@0.10.5'
