use std::{
  env,
  fs,
  path::{Path, PathBuf},
};

fn main() {
  println!("cargo:rerun-if-changed=src/methods.rs");
  let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
  let methods_source = fs::read_to_string(manifest_dir.join("src/methods.rs"))
    .expect("read src/methods.rs");
  let names = extract_method_names(&methods_source);

  let out_dir = manifest_dir
    .parent()
    .and_then(Path::parent)
    .expect("workspace root")
    .join("jsb/src/generated/jsb-methods.ts");
  if let Some(parent) = out_dir.parent() {
    fs::create_dir_all(parent).expect("create generated dir");
  }
  let body = names
    .iter()
    .map(|name| format!("  | {name:?}"))
    .collect::<Vec<_>>()
    .join("\n");
  let content = format!(
    "// @generated by crates/shell360-runtime/build.rs — DO NOT EDIT.\n\
     // Source of truth: crates/shell360-runtime/src/methods.rs.\n\
     // Regenerated on every cargo build of shell360-runtime.\n\
     export type JsbMethod =\n{body};\n",
  );
  fs::write(&out_dir, content).expect("write generated ts");
}

/// Extracts the ordered method names from the `host_methods` and
/// `rust_methods` string arrays declared in `methods.rs`. Each name appears
/// exactly once in the output, in declaration order.
fn extract_method_names(source: &str) -> Vec<String> {
  let mut names = Vec::new();
  let mut in_target_array = false;
  let mut depth = 0u32;
  for line in source.lines() {
    let trimmed = line.trim_start();
    if !in_target_array {
      if trimmed.starts_with("let host_methods")
        || trimmed.starts_with("let rust_methods")
      {
        in_target_array = true;
        depth = count_open_brackets(trimmed);
        capture_names_in_line(trimmed, &mut names);
        if depth == 0 {
          in_target_array = false;
        }
      }
      continue;
    }
    capture_names_in_line(line, &mut names);
    depth = adjust_depth(depth, line);
    if depth == 0 {
      in_target_array = false;
    }
  }
  names
}

fn capture_names_in_line(line: &str, names: &mut Vec<String>) {
  let bytes = line.as_bytes();
  let mut i = 0;
  while i < bytes.len() {
    if bytes[i] == b'"' {
      let start = i + 1;
      let mut end = start;
      while end < bytes.len() && bytes[end] != b'"' {
        if bytes[end] == b'\\' {
          end += 1;
        }
        end += 1;
      }
      if end <= bytes.len() {
        if let Ok(name) = std::str::from_utf8(&bytes[start..end]) {
          names.push(name.to_string());
        }
        i = end + 1;
        continue;
      }
    }
    i += 1;
  }
}

fn count_open_brackets(line: &str) -> u32 {
  let opens = line.bytes().filter(|&b| b == b'[').count() as u32;
  let closes = line.bytes().filter(|&b| b == b']').count() as u32;
  opens.saturating_sub(closes)
}

fn adjust_depth(depth: u32, line: &str) -> u32 {
  let opens = line.bytes().filter(|&b| b == b'[').count() as u32;
  let closes = line.bytes().filter(|&b| b == b']').count() as u32;
  depth + opens - closes
}