[package]
name = "shell360-napi"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
strip = "symbols"

[build-dependencies]
napi-build = "2.4.1"

[dependencies]
napi = { version = "3.12.1", features = ["napi10"] }
napi-derive = "3.6.3"
shell360-ffi = { path = "../shell360-ffi" }
