export type KeyboardLayoutName = "Lowercase" | "Uppercase" | "Fn" | "Symbols";

export const KEYBOARD_LAYOUT: Record<KeyboardLayoutName, string[][]> = {
  Lowercase: [
    ["Ctrl", "Shift", "Alt", "Esc", "Tab"],
    ["1", "2", "3", "4", "5", "6", "7", "8", "9", "0"],
    ["q", "w", "e", "r", "t", "y", "u", "i", "o", "p"],
    ["a", "s", "d", "f", "g", "h", "j", "k", "l"],
    ["Caps", "z", "x", "c", "v", "b", "n", "m"],
    ["Fn", "...", "Space", "⌫", "Enter"],
  ],
  Uppercase: [
    ["Ctrl", "Shift", "Alt", "Esc", "Tab"],
    ["1", "2", "3", "4", "5", "6", "7", "8", "9", "0"],
    ["Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P"],
    ["A", "S", "D", "F", "G", "H", "J", "K", "L"],
    ["Caps", "Z", "X", "C", "V", "B", "N", "M"],
    ["Fn", "...", "Space", "⌫", "Enter"],
  ],
  Fn: [
    ["Ctrl", "Shift", "Alt", "Esc", "Tab"],
    ["F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "F10"],
    ["F11", "F12", "Ins", "Del", "Home", "End"],
    ["PgUp", "PgDn", "←", "↑", "→", "↓"],
    [";", "=", ",", "-", "."],
    ["/", "`", "[", "\\", "]", "'"],
    ["Fn", "...", "Space", "⌫", "Enter"],
  ],
  Symbols: [
    ["Ctrl", "Shift", "Alt", "Esc", "Tab"],
    ["^W", "^R", "^A", "^E", "^C", "^L"],
    ["^S", "^Z", "^X", "^D", "^N", "^P"],
    // ["`", "~", "-", "=", "_", "|", "[", "]", "\\"],
    // [";", "'", ",", ".", "/", '"', "<", ">"],
    ["Fn", "...", "Space", "⌫", "Enter"],
  ],
};

export const KEYBOARD_KEY_WIDTH: Record<string, number> = {
  Ctrl: 1.2,
  Shift: 1.2,
  Alt: 1.2,
  Esc: 1.2,
  Tab: 1.2,
  Caps: 1.2,
  Fn: 1.1,
  "...": 1.1,
  Space: 2.8,
  "⌫": 1.8,
  Enter: 1.8,
};

export type KeyboardModifierToken = "Ctrl" | "Alt" | "Shift";

export const KEYBOARD_MODIFIER_TOKENS: Array<KeyboardModifierToken> = [
  "Ctrl",
  "Shift",
  "Alt",
];

export type KeyboardLayoutToken = "Caps" | "Fn" | "...";

export const KEYBOARD_LAYOUT_TOKENS: Array<KeyboardLayoutToken> = [
  "Caps",
  "Fn",
  "...",
];

export const TOKEN_TO_KEY_EVENT_INIT: Record<
  string,
  Partial<KeyboardEventInit>
> = {
  "⌫": { keyCode: 8, key: "Backspace", code: "Backspace" },
  Tab: { keyCode: 9, key: "Tab", code: "Tab" },
  Enter: { keyCode: 13, key: "Enter", code: "Enter" },
  Shift: { keyCode: 16, key: "Shift", code: "ShiftLeft", shiftKey: true },
  Ctrl: { keyCode: 17, key: "Control", code: "ControlLeft", ctrlKey: true },
  Alt: { keyCode: 18, key: "Alt", code: "AltLeft", altKey: true },
  Caps: { keyCode: 20, key: "CapsLock", code: "CapsLock" },
  Esc: { keyCode: 27, key: "Escape", code: "Escape" },
  Space: { keyCode: 32, key: " ", code: "Space" },
  PgUp: { keyCode: 33, key: "PageUp", code: "PageUp" },
  PgDn: { keyCode: 34, key: "PageDown", code: "PageDown" },
  End: { keyCode: 35, key: "End", code: "End" },
  Home: { keyCode: 36, key: "Home", code: "Home" },
  "←": { keyCode: 37, key: "ArrowLeft", code: "ArrowLeft" },
  "↑": { keyCode: 38, key: "ArrowUp", code: "ArrowUp" },
  "→": { keyCode: 39, key: "ArrowRight", code: "ArrowRight" },
  "↓": { keyCode: 40, key: "ArrowDown", code: "ArrowDown" },
  Ins: { keyCode: 45, key: "Insert", code: "Insert" },
  Del: { keyCode: 46, key: "Delete", code: "Delete" },
  0: { keyCode: 48, key: "0", code: "Digit0" },
  1: { keyCode: 49, key: "1", code: "Digit1" },
  2: { keyCode: 50, key: "2", code: "Digit2" },
  3: { keyCode: 51, key: "3", code: "Digit3" },
  4: { keyCode: 52, key: "4", code: "Digit4" },
  5: { keyCode: 53, key: "5", code: "Digit5" },
  6: { keyCode: 54, key: "6", code: "Digit6" },
  7: { keyCode: 55, key: "7", code: "Digit7" },
  8: { keyCode: 56, key: "8", code: "Digit8" },
  9: { keyCode: 57, key: "9", code: "Digit9" },
  a: { keyCode: 65, key: "a", code: "KeyA" },
  b: { keyCode: 66, key: "b", code: "KeyB" },
  c: { keyCode: 67, key: "c", code: "KeyC" },
  d: { keyCode: 68, key: "d", code: "KeyD" },
  e: { keyCode: 69, key: "e", code: "KeyE" },
  f: { keyCode: 70, key: "f", code: "KeyF" },
  g: { keyCode: 71, key: "g", code: "KeyG" },
  h: { keyCode: 72, key: "h", code: "KeyH" },
  i: { keyCode: 73, key: "i", code: "KeyI" },
  j: { keyCode: 74, key: "j", code: "KeyJ" },
  k: { keyCode: 75, key: "k", code: "KeyK" },
  l: { keyCode: 76, key: "l", code: "KeyL" },
  m: { keyCode: 77, key: "m", code: "KeyM" },
  n: { keyCode: 78, key: "n", code: "KeyN" },
  o: { keyCode: 79, key: "o", code: "KeyO" },
  p: { keyCode: 80, key: "p", code: "KeyP" },
  q: { keyCode: 81, key: "q", code: "KeyQ" },
  r: { keyCode: 82, key: "r", code: "KeyR" },
  s: { keyCode: 83, key: "s", code: "KeyS" },
  t: { keyCode: 84, key: "t", code: "KeyT" },
  u: { keyCode: 85, key: "u", code: "KeyU" },
  v: { keyCode: 86, key: "v", code: "KeyV" },
  w: { keyCode: 87, key: "w", code: "KeyW" },
  x: { keyCode: 88, key: "x", code: "KeyX" },
  y: { keyCode: 89, key: "y", code: "KeyY" },
  z: { keyCode: 90, key: "z", code: "KeyZ" },
  A: { keyCode: 65, key: "A", code: "KeyA" },
  B: { keyCode: 66, key: "B", code: "KeyB" },
  C: { keyCode: 67, key: "C", code: "KeyC" },
  D: { keyCode: 68, key: "D", code: "KeyD" },
  E: { keyCode: 69, key: "E", code: "KeyE" },
  F: { keyCode: 70, key: "F", code: "KeyF" },
  G: { keyCode: 71, key: "G", code: "KeyG" },
  H: { keyCode: 72, key: "H", code: "KeyH" },
  I: { keyCode: 73, key: "I", code: "KeyI" },
  J: { keyCode: 74, key: "J", code: "KeyJ" },
  K: { keyCode: 75, key: "K", code: "KeyK" },
  L: { keyCode: 76, key: "L", code: "KeyL" },
  M: { keyCode: 77, key: "M", code: "KeyM" },
  N: { keyCode: 78, key: "N", code: "KeyN" },
  O: { keyCode: 79, key: "O", code: "KeyO" },
  P: { keyCode: 80, key: "P", code: "KeyP" },
  Q: { keyCode: 81, key: "Q", code: "KeyQ" },
  R: { keyCode: 82, key: "R", code: "KeyR" },
  S: { keyCode: 83, key: "S", code: "KeyS" },
  T: { keyCode: 84, key: "T", code: "KeyT" },
  U: { keyCode: 85, key: "U", code: "KeyU" },
  V: { keyCode: 86, key: "V", code: "KeyV" },
  W: { keyCode: 87, key: "W", code: "KeyW" },
  X: { keyCode: 88, key: "X", code: "KeyX" },
  Y: { keyCode: 89, key: "Y", code: "KeyY" },
  Z: { keyCode: 90, key: "Z", code: "KeyZ" },
  F1: { keyCode: 112, key: "F1", code: "F1" },
  F2: { keyCode: 113, key: "F2", code: "F2" },
  F3: { keyCode: 114, key: "F3", code: "F3" },
  F4: { keyCode: 115, key: "F4", code: "F4" },
  F5: { keyCode: 116, key: "F5", code: "F5" },
  F6: { keyCode: 117, key: "F6", code: "F6" },
  F7: { keyCode: 118, key: "F7", code: "F7" },
  F8: { keyCode: 119, key: "F8", code: "F8" },
  F9: { keyCode: 120, key: "F9", code: "F9" },
  F10: { keyCode: 121, key: "F10", code: "F10" },
  F11: { keyCode: 122, key: "F11", code: "F11" },
  F12: { keyCode: 123, key: "F12", code: "F12" },
  ";": { keyCode: 186, key: ";", code: "Semicolon" },
  "=": { keyCode: 187, key: "=", code: "Equal" },
  ",": { keyCode: 188, key: ",", code: "Comma" },
  "-": { keyCode: 189, key: "-", code: "Minus" },
  ".": { keyCode: 190, key: ".", code: "Period" },
  "/": { keyCode: 191, key: "/", code: "Slash" },
  "`": { keyCode: 192, key: "`", code: "Backquote" },
  "[": { keyCode: 219, key: "[", code: "BracketLeft" },
  "\\": { keyCode: 220, key: "\\", code: "Backslash" },
  "]": { keyCode: 221, key: "]", code: "BracketRight" },
  "'": { keyCode: 222, key: "'", code: "Quote" },
  "^W": { keyCode: 87, key: "w", code: "KeyW", ctrlKey: true },
  "^R": { keyCode: 82, key: "r", code: "KeyR", ctrlKey: true },
  "^A": { keyCode: 65, key: "a", code: "KeyA", ctrlKey: true },
  "^E": { keyCode: 69, key: "e", code: "KeyE", ctrlKey: true },
  "^C": { keyCode: 67, key: "c", code: "KeyC", ctrlKey: true },
  "^L": { keyCode: 76, key: "l", code: "KeyL", ctrlKey: true },
  "^S": { keyCode: 83, key: "s", code: "KeyS", ctrlKey: true },
  "^Z": { keyCode: 90, key: "z", code: "KeyZ", ctrlKey: true },
  "^X": { keyCode: 88, key: "x", code: "KeyX", ctrlKey: true },
  "^D": { keyCode: 68, key: "d", code: "KeyD", ctrlKey: true },
  "^N": { keyCode: 78, key: "n", code: "KeyN", ctrlKey: true },
  "^P": { keyCode: 80, key: "p", code: "KeyP", ctrlKey: true },
};
