package com.nashaofu.shell360.ui.theme

import androidx.compose.ui.graphics.Color

val ShellGreen = Color(0xFF216E45)
val ShellOnGreen = Color(0xFFFFFFFF)
val ShellGreenContainer = Color(0xFFB6F1C9)
val ShellOnGreenContainer = Color(0xFF002110)
val ShellSecondary = Color(0xFF4F6356)
val ShellOnSecondary = Color(0xFFFFFFFF)
val ShellSecondaryContainer = Color(0xFFD2E8D7)
val ShellOnSecondaryContainer = Color(0xFF0C1F13)
val ShellBackground = Color(0xFFF9FBF8)
val ShellOnBackground = Color(0xFF191D19)
val ShellSurface = Color(0xFFFFFFFF)
val ShellOnSurface = Color(0xFF191D19)
val ShellSurfaceVariant = Color(0xFFDDE8DE)
val ShellOnSurfaceVariant = Color(0xFF414941)
val ShellOutline = Color(0xFF717971)
val ShellOutlineVariant = Color(0xFFC1CCC1)
val ShellError = Color(0xFFBA1A1A)
val ShellOnError = Color(0xFFFFFFFF)
val ShellErrorContainer = Color(0xFFFFDAD6)
val ShellOnErrorContainer = Color(0xFF410002)

val ShellDarkGreen = Color(0xFF8BD5A7)
val ShellDarkOnGreen = Color(0xFF00391F)
val ShellDarkGreenContainer = Color(0xFF00532E)
val ShellDarkOnGreenContainer = Color(0xFFB6F1C9)
val ShellDarkSecondary = Color(0xFFB4CCB9)
val ShellDarkOnSecondary = Color(0xFF20352A)
val ShellDarkSecondaryContainer = Color(0xFF354B3C)
val ShellDarkOnSecondaryContainer = Color(0xFFD0E8D4)
val ShellDarkBackground = Color(0xFF101411)
val ShellDarkOnBackground = Color(0xFFE1E4DF)
val ShellDarkSurface = Color(0xFF191D19)
val ShellDarkOnSurface = Color(0xFFE1E4DF)
val ShellDarkSurfaceVariant = Color(0xFF414941)
val ShellDarkOnSurfaceVariant = Color(0xFFC1CCC1)
val ShellDarkOutline = Color(0xFF8B938B)
val ShellDarkOutlineVariant = Color(0xFF414941)
val ShellDarkError = Color(0xFFFFB4AB)
val ShellDarkOnError = Color(0xFF690005)
val ShellDarkErrorContainer = Color(0xFF93000A)
val ShellDarkOnErrorContainer = Color(0xFFFFDAD6)
