[default]
description = "Default permissions for the plugin"
permissions = [
  "allow-session-connect",
  "allow-session-authenticate",
  "allow-session-disconnect",
  "allow-shell-open",
  "allow-shell-close",
  "allow-shell-resize",
  "allow-shell-send",
  "allow-port-forwarding-local-open",
  "allow-port-forwarding-local-close",
  "allow-port-forwarding-remote-open",
  "allow-port-forwarding-remote-close",
  "allow-port-forwarding-dynamic-open",
  "allow-port-forwarding-dynamic-close",
  "allow-sftp-open",
  "allow-sftp-close",
  "allow-sftp-read-dir",
  "allow-sftp-upload-file",
  "allow-sftp-download-file",
  "allow-sftp-create-file",
  "allow-sftp-create-dir",
  "allow-sftp-remove-dir",
  "allow-sftp-remove-file",
  "allow-sftp-rename",
  "allow-sftp-exists",
  "allow-sftp-canonicalize",
]
