[default]
description = "Default permissions for the plugin"
permissions = [
  "allow-ssh-connect",
  "allow-ssh-authenticate",
  "allow-ssh-shell",
  "allow-ssh-disconnect",
  "allow-ssh-resize",
  "allow-ssh-send",
  "allow-ssh-open-local-port-forwarding",
  "allow-ssh-close-local-port-forwarding",
  "allow-ssh-open-remote-port-forwarding",
  "allow-ssh-close-remote-port-forwarding",
  "allow-ssh-open-dynamic-port-forwarding",
  "allow-ssh-close-dynamic-port-forwarding",
  "allow-sftp-connect",
  "allow-sftp-authenticate",
  "allow-sftp-channel",
  "allow-sftp-disconnect",
  "allow-sftp-read-dir",
  "allow-sftp-upload-file",
  "allow-sftp-download-file",
  "allow-sftp-create-file",
  "allow-sftp-create-dir",
  "allow-sftp-remove-dir",
  "allow-sftp-remove-file",
  "allow-sftp-rename",
  "allow-sftp-exists",
  "allow-sftp-canonicalize",
]
